name: Aggregate

on:
  - push:
    branches:
      - master
  - schedule:
    # Run every Friday at 12:00 PM (noon) UTC
    - cron: '0 12 * * 5'

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: Install dependencies
        run: | 
          julia --project=docs --color=yes -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
          julia --project=docs --color=yes -e 'using Pkg; Pkg.add("Documenter"); Pkg.add("MultiDocumenter"); Pkg.add("LibGit2")'
      - name: Aggregate and deploy
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          julia --project=docs --color=yes docs/makeall.jl deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
